name: Build and Release

on:
  push:
    tags:
      - 'release*'  # 监听以 release 开头的标签

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/release-}" >> $GITHUB_ENV

      - name: Generate release notes
        id: generate_notes
        run: |
          echo "Changes in this release:" > release_notes.txt
          git log --pretty=format:"- %s by @%an" >> release_notes.txt
        # This will create notes like: "- Commit message by @username"

      - name: Build
        run: cargo build --release

      - name: Package
        run: |
          mkdir -p release
          cp target/release/testfs release/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: ${{ env.VERSION }}
          body_path: release_notes.txt  # 使用生成的 release_notes.txt 作为发布说明
          files: release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
